version: '3.9'

services:
  postgres_e2e:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hockey_hub_password
      POSTGRES_DB: hockey_hub_training_e2e
    ports:
      - '5442:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10

  redis_e2e:
    image: redis:7-alpine
    ports:
      - '6387:6379'
    command: ["redis-server", "--appendonly", "no"]
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10


